import { addDays } from "@/lib/format";
import type { Lead } from "./types";

/**
 * Mock, in-memory seed data for the Sales Manager Lead Pipeline screens.
 *
 * This is NOT read from or written to the database. It exists so the UI is
 * functional and testable while the real data-model question (how this
 * prototype's stages/fields map onto `customers`/`mbos_leads`) is decided
 * separately. Every lead below is fictional.
 */
/** The fixed business date the mock book is seeded around, as a calendar
 * date — never derived from a Date, which would answer in UTC. */
export const MOCK_TODAY = "2026-09-23";

export function seedLeads(): Lead[] {
  const iso = (offsetDays: number) => addDays(MOCK_TODAY, offsetDays);

  const leads: Lead[] = [
    {
      id: "LD-3101",
      name: "Konkan Hardware & Paints",
      city: "Ratnagiri",
      contact: "Vinayak Sawant",
      phone: "9822011001",
      email: "vinayak.sawant@konkanhardware.in",
      address: "Shop 4, Ganesh Chowk, Ratnagiri, Maharashtra 415612",
      source: "Field visit",
      createdAt: iso(-9),
      salesType: "direct",
      stage: "suspect",
      priority: "medium",
      owner: "rahul",
      manager: "amit",
      gstVerified: false,
      visits: 1,
      verification: { done: false, result: null },
      qualChecks: {},
      comms: {},
      nextAction: "Second suspect visit — confirm requirement",
      nextActionDate: iso(2),
      nextActionResp: "rahul",
      expectedOutcome: "Decide Prospect or Not Prospect",
      timeline: [
        { d: iso(-9), kind: "system", title: "Lead created", meta: "Source: Field visit" },
        { d: iso(-6), kind: "salesman", title: "Suspect visit logged" },
      ],
    },
    {
      id: "LD-3102",
      name: "Shree Coatings",
      city: "Nashik",
      contact: "Vaibhav Shirke",
      phone: "9822011002",
      email: "vaibhav.shirke@shreecoatings.in",
      address: "12, MIDC Industrial Area, Satpur, Nashik, Maharashtra 422007",
      source: "Referral",
      createdAt: iso(-16),
      salesType: "direct",
      stage: "prospect",
      priority: "high",
      owner: "rahul",
      manager: "amit",
      product: "Mahek Enamel Thinner",
      application: "Furniture spray booth",
      monthlyLitres: 2200,
      potentialPaise: 18500000,
      competitor: "Berger",
      decisionMaker: "Vaibhav Shirke (Proprietor)",
      customerType: "Hardware retailer",
      gstVerified: false,
      visits: 3,
      conversionReason: "agreed_trial",
      verification: { done: false, result: null },
      qualChecks: {},
      comms: {},
      nextAction: "Manager verification call",
      nextActionDate: iso(-1),
      nextActionResp: "amit",
      expectedOutcome: "Verify the visit and open qualification",
      timeline: [
        { d: iso(-16), kind: "system", title: "Lead created", meta: "Source: Referral" },
        { d: iso(-10), kind: "salesman", title: "Converted to Prospect", meta: "Reason: Customer agreed to a product trial" },
        { d: iso(-10), kind: "system", title: "Sales Manager notified — became Lead Manager" },
        { d: iso(-10), kind: "system", title: "Customer verification call task raised" },
      ],
    },
    {
      id: "LD-3103",
      name: "Om Industrial Solutions",
      city: "Nashik",
      contact: "Om Deshpande",
      phone: "9822011003",
      email: "om.deshpande@omindustrial.in",
      address: "Plot 7, Ambad Industrial Estate, Nashik, Maharashtra 422010",
      source: "Website enquiry",
      createdAt: iso(-24),
      salesType: "direct",
      stage: "prospect",
      priority: "medium",
      owner: "sunil",
      manager: "amit",
      product: "Mahek GP Thinner",
      application: "General purpose thinning",
      monthlyLitres: 900,
      potentialPaise: 7000000,
      competitor: "Local unbranded",
      decisionMaker: "Om Deshpande (Partner)",
      customerType: "Industrial buyer",
      gstin: "27ABCDE1234F1Z5",
      gstVerified: true,
      visits: 2,
      conversionReason: "price_interest",
      verification: {
        done: true,
        result: "verified",
        explainedWell: true,
        currentProduct: "Locally sourced unbranded thinner",
        impression: "Found him knowledgeable and prompt.",
        genuineInterest: true,
        priceConcern: true,
        readyForTrial: true,
      },
      qualChecks: {},
      comms: {},
      nextAction: "Open qualification checklist",
      nextActionDate: iso(0),
      nextActionResp: "sunil",
      expectedOutcome: "Move to Qualification",
      timeline: [
        { d: iso(-24), kind: "system", title: "Lead created", meta: "Source: Website enquiry" },
        { d: iso(-14), kind: "salesman", title: "Converted to Prospect", meta: "Reason: Price or commercial interest" },
        { d: iso(-4), kind: "sales_manager", title: "Verification Result: Verified" },
      ],
    },
    {
      id: "LD-3104",
      name: "ABC Paints & Hardware",
      city: "Nashik",
      contact: "Suresh Rane",
      phone: "9822011004",
      email: "suresh.rane@abcpaints.in",
      address: "45, College Road, Nashik, Maharashtra 422005",
      source: "Field visit",
      createdAt: iso(-40),
      salesType: "direct",
      stage: "qualification",
      priority: "high",
      owner: "rahul",
      manager: "amit",
      product: "Mahek Polish Thinner M1433",
      application: "Furniture polish thinning",
      monthlyLitres: 1500,
      potentialPaise: 12000000,
      competitor: "Asian Paints",
      decisionMaker: "Suresh Rane (Proprietor)",
      customerType: "Hardware retailer",
      gstin: "27PQRSX5678G1Z2",
      gstVerified: false,
      creditDaysWanted: 30,
      buyer: "Suresh Rane",
      visits: 4,
      conversionReason: "significant_potential",
      verification: {
        done: true,
        result: "verified_with_corrections",
        explainedWell: true,
        currentProduct: "Asian Paints thinner",
        impression: "Salesman was thorough and answered every question.",
        genuineInterest: true,
        creditConcern: true,
        deliveryConcern: true,
        readyForTrial: true,
        readyForCommercial: true,
      },
      verificationCorrections: [
        { field: "Monthly requirement", original: "1,200 L", corrected: "1,500 L", reason: "Customer corrected the figure on the call" },
      ],
      qualChecks: {
        gst_verified: false,
        application_understood: true,
        price_discussed: true,
        credit_days: true,
        delivery_discussed: true,
        authorized_buyer: true,
        agrees_to_test: true,
        next_step_agreed: false,
      },
      comms: { call: true, price_list: true },
      nextAction: "Confirm GST verification and close qualification",
      nextActionDate: iso(1),
      nextActionResp: "amit",
      expectedOutcome: "All 8 conditions met — ready for Sample / Trial",
      timeline: [
        { d: iso(-40), kind: "system", title: "Lead created", meta: "Source: Field visit" },
        { d: iso(-28), kind: "salesman", title: "Converted to Prospect" },
        { d: iso(-18), kind: "sales_manager", title: "Verification Result: Verified" },
        { d: iso(-6), kind: "salesman", title: "6 of 8 qualification conditions marked done" },
      ],
    },
    {
      id: "LD-3105",
      name: "Metro Hardware Depot",
      city: "Pune",
      contact: "Imran Sheikh",
      phone: "9822011005",
      email: "imran.sheikh@metrohardware.in",
      address: "23, FC Road, Shivajinagar, Pune, Maharashtra 411005",
      source: "Referral",
      createdAt: iso(-52),
      salesType: "direct",
      stage: "sample_trial",
      priority: "medium",
      owner: "meera",
      manager: "amit",
      product: "Mahek Mild Cleaner M164",
      application: "Surface prep before repainting",
      monthlyLitres: 700,
      potentialPaise: 5200000,
      competitor: "Nerolac",
      decisionMaker: "Imran Sheikh (Proprietor)",
      customerType: "Hardware retailer",
      gstin: "27HIJKL9012M1Z8",
      gstVerified: true,
      creditDaysWanted: 15,
      visits: 3,
      verification: {
        done: true,
        result: "verified",
        explainedWell: true,
        currentProduct: "Nerolac thinner",
        impression: "Confident and professional.",
        genuineInterest: true,
        readyForTrial: true,
      },
      qualChecks: Object.fromEntries(
        ["gst_verified", "application_understood", "price_discussed", "credit_days", "delivery_discussed", "authorized_buyer", "agrees_to_test", "next_step_agreed"].map((k) => [k, true]),
      ),
      sample: {
        state: "dispatched",
        quantity: "5 L can",
        reason: "Customer requested it",
        courier: "Blue Speed Logistics",
        docket: "BSL-88213",
        promisedDeliveryAt: iso(2),
        dispatchedAt: iso(-1),
        feedbackRecorded: false,
        trialOutcome: "pending",
        chase: [],
      },
      comms: { call: true, sample_followup: true },
      nextAction: "Confirm sample received with customer",
      nextActionDate: iso(2),
      nextActionResp: "meera",
      expectedOutcome: "Mark sample received",
      timeline: [
        { d: iso(-52), kind: "system", title: "Lead created" },
        { d: iso(-30), kind: "sales_manager", title: "Verification Result: Verified" },
        { d: iso(-12), kind: "system", title: "All 8 conditions met — ready for Sample / Trial" },
        { d: iso(-1), kind: "sales_manager", title: "Sample dispatched", meta: "Blue Speed Logistics · BSL-88213" },
      ],
    },
    {
      id: "LD-3106",
      name: "Deshmukh Traders",
      city: "Nashik",
      contact: "Prakash Deshmukh",
      phone: "9822011006",
      email: "prakash.deshmukh@deshmukhtraders.in",
      address: "8, Panchavati Road, Nashik, Maharashtra 422003",
      source: "Field visit",
      createdAt: iso(-64),
      salesType: "direct",
      stage: "sample_received",
      priority: "low",
      owner: "rahul",
      manager: "amit",
      product: "Mahek Mild Cleaner M164",
      monthlyLitres: 500,
      potentialPaise: 4000000,
      competitor: "Local unbranded",
      customerType: "Hardware retailer",
      gstVerified: true,
      visits: 3,
      verification: {
        done: true,
        result: "verified",
        explainedWell: true,
        currentProduct: "No branded product currently",
        impression: "Very cooperative.",
        genuineInterest: true,
        readyForTrial: true,
      },
      qualChecks: Object.fromEntries(
        ["gst_verified", "application_understood", "price_discussed", "credit_days", "delivery_discussed", "authorized_buyer", "agrees_to_test", "next_step_agreed"].map((k) => [k, true]),
      ),
      sample: {
        state: "received",
        quantity: "5 L can",
        reason: "New application",
        courier: "Own delivery",
        dispatchedAt: iso(-8),
        receivedAt: iso(-5),
        feedbackRecorded: false,
        trialOutcome: "pending",
        chase: [
          { label: "Day-2 review chase", d: iso(-3), done: true },
          { label: "Day-4 review chase", d: iso(-1), done: true },
          { label: "Day-6 review chase", d: iso(1), done: false },
        ],
      },
      comms: { call: true },
      nextAction: "Record trial review",
      nextActionDate: iso(1),
      nextActionResp: "amit",
      expectedOutcome: "Trial feedback recorded",
      timeline: [
        { d: iso(-64), kind: "system", title: "Lead created" },
        { d: iso(-8), kind: "sales_manager", title: "Sample dispatched" },
        { d: iso(-5), kind: "salesman", title: "Sample received, confirmed by customer" },
      ],
    },
    {
      id: "LD-3107",
      name: "Sindhudurg Building Supplies",
      city: "Kudal",
      contact: "Ganesh Patil",
      phone: "9822011007",
      email: "ganesh.patil@sindhudurgbuilding.in",
      address: "Main Road, Kudal, Sindhudurg, Maharashtra 416520",
      source: "Field visit",
      createdAt: iso(-80),
      salesType: "third_party",
      stage: "sample_review",
      priority: "medium",
      owner: "sunil",
      manager: "amit",
      distributor: "Konkan Coatings Distributors",
      distributorSalesman: "Ravi Naik",
      product: "Mahek GP Thinner",
      monthlyLitres: 350,
      potentialPaise: 2600000,
      customerType: "Hardware retailer",
      gstVerified: true,
      visits: 2,
      verification: {
        done: true,
        result: "verified_with_corrections",
        explainedWell: true,
        currentProduct: "Buys through Konkan Coatings Distributors currently",
        impression: "Positive; wants to compare quality directly.",
        genuineInterest: true,
        competitorConcern: true,
        readyForTrial: true,
      },
      verificationCorrections: [
        { field: "Decision maker", original: "Ganesh Patil", corrected: "Ganesh Patil (with his son Mahesh co-deciding)", reason: "Salesman spoke to the son; shop is actually a joint decision" },
      ],
      qualChecks: Object.fromEntries(
        ["gst_verified", "application_understood", "price_discussed", "credit_days", "delivery_discussed", "authorized_buyer", "agrees_to_test", "next_step_agreed"].map((k) => [k, true]),
      ),
      sample: {
        state: "reviewed",
        quantity: "5 L can",
        reason: "Compare against competitor / current product",
        dispatchedAt: iso(-20),
        receivedAt: iso(-17),
        feedbackRecorded: true,
        feedback: "Matched their benchmark on drying time; slightly better coverage than what they use now.",
        trialOutcome: "approved",
        chase: [],
      },
      comms: { call: true, negotiation_call: true },
      nextAction: "Move to Negotiation",
      nextActionDate: iso(0),
      nextActionResp: "amit",
      expectedOutcome: "Open negotiation",
      timeline: [
        { d: iso(-80), kind: "system", title: "Lead created" },
        { d: iso(-17), kind: "salesman", title: "Sample received" },
        { d: iso(-10), kind: "sales_manager", title: "Trial review recorded", meta: "Approved" },
      ],
    },
    {
      id: "LD-3108",
      name: "Sunrise Hardware & Paints",
      city: "Aurangabad",
      contact: "Kiran Bhosale",
      phone: "9822011008",
      email: "kiran.bhosale@sunrisehardware.in",
      address: "17, Jalna Road, Aurangabad, Maharashtra 431001",
      source: "Field visit",
      createdAt: iso(-96),
      salesType: "direct",
      stage: "negotiation",
      priority: "high",
      owner: "rahul",
      manager: "amit",
      product: "Mahek Polish Thinner M1433",
      monthlyLitres: 2200,
      potentialPaise: 18500000,
      customerType: "Hardware retailer",
      gstVerified: true,
      visits: 5,
      verification: {
        done: true,
        result: "verified",
        explainedWell: true,
        currentProduct: "Asian Paints thinner",
        impression: "Strong rapport built over multiple visits.",
        genuineInterest: true,
        readyForTrial: true,
        readyForCommercial: true,
        readyForOrder: true,
      },
      qualChecks: Object.fromEntries(
        ["gst_verified", "application_understood", "price_discussed", "credit_days", "delivery_discussed", "authorized_buyer", "agrees_to_test", "next_step_agreed"].map((k) => [k, true]),
      ),
      sample: {
        state: "reviewed",
        feedbackRecorded: true,
        feedback: "Approved after two rounds of trial.",
        trialOutcome: "approved",
        chase: [],
      },
      negotiation: {
        quantity: "2,200 L / month",
        visitDone: true,
        blockers: ["credit_terms"],
        objection: "Wants 45-day credit instead of the standard 30.",
      },
      commitment: {
        quantity: "2,200 Litres",
        expectedOrderDate: iso(4),
        recordedBy: "amit",
        recordedAt: iso(-2),
      },
      comms: { call: true, negotiation_call: true, ask_first_order: true },
      nextAction: "Confirm the actual order once it lands",
      nextActionDate: iso(4),
      nextActionResp: "amit",
      expectedOutcome: "Confirm Actual Order → 1st Order",
      timeline: [
        { d: iso(-96), kind: "system", title: "Lead created" },
        { d: iso(-30), kind: "sales_manager", title: "Trial review recorded", meta: "Approved" },
        { d: iso(-10), kind: "system", title: "Moved to Negotiation" },
        { d: iso(-2), kind: "sales_manager", title: "Commitment recorded", meta: "2,200 Litres, expected " + iso(4) },
      ],
    },
    {
      id: "LD-3109",
      name: "Patil Engineering Works",
      city: "Nashik",
      contact: "Anil Patil",
      phone: "9822011009",
      email: "anil.patil@patilengineering.in",
      address: "Gat No. 112, Sinnar MIDC, Nashik, Maharashtra 422103",
      source: "Referral",
      createdAt: iso(-140),
      salesType: "direct",
      stage: "payment",
      priority: "medium",
      owner: "rahul",
      manager: "amit",
      product: "Mahek Polish Thinner M1433",
      monthlyLitres: 650,
      potentialPaise: 5200000,
      customerType: "Industrial buyer",
      gstVerified: true,
      visits: 6,
      verification: {
        done: true,
        result: "verified",
        explainedWell: true,
        currentProduct: "Berger thinner",
        impression: "Detail-oriented buyer, asked technical questions.",
        genuineInterest: true,
        deliveryConcern: true,
        readyForTrial: true,
        readyForCommercial: true,
        readyForOrder: true,
      },
      qualChecks: Object.fromEntries(
        ["gst_verified", "application_understood", "price_discussed", "credit_days", "delivery_discussed", "authorized_buyer", "agrees_to_test", "next_step_agreed"].map((k) => [k, true]),
      ),
      order: { amount: 52000, litres: 650, orderedAt: iso(-14), reference: "PO-4471" },
      comms: { call: true, payment_followup: true },
      nextAction: "Payment follow-up — ₹45,000 due",
      nextActionDate: iso(0),
      nextActionResp: "amit",
      expectedOutcome: "Mark payment received",
      timeline: [
        { d: iso(-140), kind: "system", title: "Lead created" },
        { d: iso(-14), kind: "sales_manager", title: "Confirmed Actual Order → First Order", meta: "PO-4471" },
        { d: iso(-9), kind: "system", title: "Order dispatched → Delivery" },
        { d: iso(-4), kind: "system", title: "Order delivered → Payment" },
      ],
    },
    {
      id: "LD-3110",
      name: "Konkan Coatings Distributors",
      city: "Ratnagiri",
      contact: "Sunil Patil",
      phone: "9822011010",
      email: "sunil.patil@konkancoatings.in",
      address: "MIDC Phase II, Ratnagiri, Maharashtra 415639",
      source: "Field visit",
      createdAt: iso(-180),
      salesType: "distributor",
      stage: "management_review",
      priority: "high",
      owner: "sunil",
      manager: "amit",
      gstVerified: true,
      visits: 4,
      verification: {
        done: true,
        result: "verified",
        explainedWell: true,
        impression: "Established distributor, well-organized operation.",
        genuineInterest: true,
        readyForCommercial: true,
      },
      qualChecks: Object.fromEntries(
        ["gst_verified", "application_understood", "price_discussed", "credit_days", "delivery_discussed", "authorized_buyer", "agrees_to_test", "next_step_agreed"].map((k) => [k, true]),
      ),
      distributorProfile: {
        gstVerified: true,
        panVerified: true,
        addressVerified: true,
        businessType: "Paint & hardware distribution",
        yearsInBusiness: 11,
        decisionMaker: "Sunil Patil (Proprietor)",
        hasDealerNetwork: true,
        activeDealers: 34,
        territoryCovered: "Ratnagiri, Sindhudurg",
        salesTeamSize: 6,
        warehouse: true,
        storageCapacityLitres: 40000,
        exclusivityRequested: true,
        discountRequested: "12% off list",
        creditLimitRequestedPaise: 350000000,
      },
      comms: { call: true },
      nextAction: "Prepare for management review",
      nextActionDate: iso(2),
      nextActionResp: "amit",
      expectedOutcome: "Management approval",
      timeline: [
        { d: iso(-180), kind: "system", title: "Lead created" },
        { d: iso(-20), kind: "sales_manager", title: "Distributor profile and terms submitted" },
        { d: iso(-6), kind: "system", title: "Escalated to management — exclusivity requested" },
      ],
    },
    {
      id: "LD-3111",
      name: "Kumar Paint House",
      city: "Nashik",
      contact: "Deepak Kumar",
      phone: "9822011011",
      email: "deepak.kumar@kumarpainthouse.in",
      address: "5, Gangapur Road, Nashik, Maharashtra 422013",
      source: "Field visit",
      createdAt: iso(-70),
      salesType: "direct",
      stage: "prospect",
      priority: "low",
      owner: "rahul",
      manager: "amit",
      product: "Mahek GP Thinner",
      monthlyLitres: 400,
      potentialPaise: 2500000,
      customerType: "Hardware retailer",
      gstVerified: false,
      visits: 2,
      conversionReason: "requested_quotation",
      verification: { done: false, result: null },
      qualChecks: {},
      comms: {},
      lost: { reason: "price", by: "amit", date: iso(-30) },
      timeline: [
        { d: iso(-70), kind: "system", title: "Lead created" },
        { d: iso(-45), kind: "salesman", title: "Converted to Prospect" },
        { d: iso(-30), kind: "sales_manager", title: "Marked Lost", meta: "Reason: Price" },
      ],
    },
    {
      id: "LD-3112",
      name: "Godavari Industrial Traders",
      city: "Nashik",
      contact: "Ramesh Godbole",
      phone: "9822011012",
      email: "ramesh.godbole@godavariindustrial.in",
      address: "Plot 21, CIDCO Industrial Area, Nashik, Maharashtra 422009",
      source: "Website enquiry",
      createdAt: iso(-210),
      salesType: "direct",
      stage: "customer",
      priority: null,
      owner: "meera",
      manager: "amit",
      product: "Mahek Enamel Thinner",
      monthlyLitres: 1100,
      potentialPaise: 9000000,
      customerType: "Industrial buyer",
      gstVerified: true,
      visits: 7,
      verification: {
        done: true,
        result: "verified",
        explainedWell: true,
        currentProduct: "Now exclusively Mahek",
        impression: "Long-standing, reliable relationship.",
        genuineInterest: true,
        readyForTrial: true,
        readyForCommercial: true,
        readyForOrder: true,
      },
      qualChecks: Object.fromEntries(
        ["gst_verified", "application_understood", "price_discussed", "credit_days", "delivery_discussed", "authorized_buyer", "agrees_to_test", "next_step_agreed"].map((k) => [k, true]),
      ),
      order: { amount: 90000, litres: 1100, orderedAt: iso(-40), reference: "PO-3390" },
      comms: { call: true, repeat_order: true },
      nextAction: undefined,
      timeline: [
        { d: iso(-210), kind: "system", title: "Lead created" },
        { d: iso(-90), kind: "sales_manager", title: "Confirmed Actual Order → First Order" },
        { d: iso(-40), kind: "system", title: "Repeat-order call" },
        { d: iso(-40), kind: "sales_manager", title: "Record second order → Customer" },
      ],
    },
    // ---------------------------------------------------------------------
    // Suspect-stage coverage for the non-"direct" sales types — LD-3101 was
    // the only Suspect lead in the seed set, and it's "direct", so there was
    // no way to click "Convert to Prospect" on a Third-Party or Distributor
    // Suspect lead and watch the classification survive into the Prospect
    // header. These two exist so that can be checked interactively, not
    // just by reading `doConvert`.
    {
      id: "LD-3113",
      name: "Sahyadri Building Mart",
      city: "Kolhapur",
      contact: "Mahesh Jadhav",
      email: "mahesh.jadhav@sahyadribuilding.in",
      address: "14, Rajarampuri, Kolhapur, Maharashtra 416008",
      source: "Field visit",
      createdAt: iso(-5),
      salesType: "third_party",
      stage: "suspect",
      priority: "medium",
      owner: "sunil",
      manager: "amit",
      gstVerified: false,
      visits: 1,
      verification: { done: false, result: null },
      qualChecks: {},
      comms: {},
      nextAction: "Second suspect visit — confirm requirement",
      nextActionDate: iso(3),
      nextActionResp: "sunil",
      expectedOutcome: "Decide Prospect or Not Prospect",
      timeline: [
        { d: iso(-5), kind: "system", title: "Lead created", meta: "Source: Field visit" },
        { d: iso(-2), kind: "salesman", title: "Suspect visit logged" },
      ],
    },
    {
      id: "LD-3114",
      name: "Vidarbha Paints & Distribution",
      city: "Nagpur",
      contact: "Ashok Wankhede",
      email: "ashok.wankhede@vidarbhapaints.in",
      address: "MIDC Hingna Road, Nagpur, Maharashtra 440016",
      source: "Referral",
      createdAt: iso(-11),
      salesType: "distributor",
      stage: "suspect",
      priority: "high",
      owner: "meera",
      manager: "amit",
      gstVerified: false,
      visits: 2,
      verification: { done: false, result: null },
      qualChecks: {},
      comms: {},
      nextAction: "Third visit — decide Prospect or Not Prospect",
      nextActionDate: iso(1),
      nextActionResp: "meera",
      expectedOutcome: "Third and final suspect visit before a decision is forced",
      timeline: [
        { d: iso(-11), kind: "system", title: "Lead created", meta: "Source: Referral" },
        { d: iso(-8), kind: "salesman", title: "Visit 1", meta: "Owner keen to discuss exclusivity for Nagpur district" },
        { d: iso(-3), kind: "salesman", title: "Visit 2", meta: "Existing warehouse inspected; runs two other paint lines" },
      ],
    },
  ];

  return leads;
}
