/* ---------------------------------------------------------------------------
 * The factory app's words, in the three languages the floor reads.
 *
 * PURE and client-safe. Copied from the design ("Mahek Factory App") word for
 * word: these sentences were written for somebody who reads slowly, and a
 * rewrite here is a rewrite of the screen.
 * ------------------------------------------------------------------------- */

export const L = {
  en:{ signIn:'Sign in', yourMobile:'Enter your mobile number', smsCode:'Enter the SMS code', forgotPin:'Forgot PIN? Get an SMS code', notFound:'We do not know this number. Check it, or ask HR.', inactive:'You cannot sign in. Please meet HR in the office.', resend:'Send the code again', resendIn:'Send again in', whoAreYou:'Who are you?', tapPhoto:'Tap your photo', scanBadge:'Scan my badge', enterPin:'Enter your PIN', notYou:'Not me', wrongPin:'Wrong PIN. Try again.', scanQR:'Scan QR', scanAny:'Scan a label to start', myTasks:'My work today', start:'Start', cont:'Continue', done:'Done', next:'Next', back:'Back', isRight:'Is this the right product?', yes:'Yes, correct', wrong:'No, wrong', team:'Team', change:'Change', used:'Used', scanLabel:'Scan label', scanAgain:'Scan again', found:'Found', manualWarn:'You picked this from a photo. Your supervisor will check it.', testLabels:'No camera here. Tap a label to scan it.', noLabel:'Label torn? Pick from photos', listen:'Listen', submit:'Send', sending:'Sending…', completed:'Saved', pending:'Waiting to send', failed:'Not saved', retry:'Try again', nextTask:'Next task', home:'Home', help:'Help', sync:'Sending', mixing:'Mixing', filling:'Filling', packing:'Packing', dispatch:'Dispatch', stopped:'Did the machine stop?', noStop:'No', minutes:'minutes', check:'Check and send', today:'Today', review:'Review', teams:'Teams', machines:'Machines', ok:'OK', printLabel:'Print QR label', signOut:'Sign out', language:'Language', waitingSend:'jobs waiting to send', allSaved:'All your work is saved', scanHint:'Hold the QR inside the box', online:'Online', weak:'Weak network', offline:'No network', scan:'Scan', fixIt:'Fix it' },
  hi:{ signIn:'साइन इन', yourMobile:'अपना मोबाइल नंबर डालें', smsCode:'SMS कोड डालें', forgotPin:'PIN भूल गए? SMS कोड लें', notFound:'यह नंबर Mahek One में नहीं है। नंबर जाँचें या HR से जुड़वाएँ।', inactive:'आपका खाता चालू नहीं है। ऑफिस में HR से मिलें।', resend:'कोड फिर से भेजें', resendIn:'फिर से भेजें', whoAreYou:'आप कौन हैं?', tapPhoto:'अपनी फोटो पर टैप करें', scanBadge:'मेरा बैज स्कैन करें', enterPin:'अपना PIN डालें', notYou:'मैं नहीं हूँ', wrongPin:'PIN गलत है। फिर से डालें।', scanQR:'QR स्कैन करें', scanAny:'शुरू करने के लिए कोई भी Mahek लेबल स्कैन करें', myTasks:'आज का मेरा काम', start:'शुरू करें', cont:'जारी रखें', done:'हो गया', next:'आगे', back:'पीछे', isRight:'क्या यही प्रोडक्ट है?', yes:'हाँ, सही है', wrong:'नहीं, गलत', team:'टीम', change:'बदलें', used:'इस्तेमाल', scanLabel:'लेबल स्कैन करें', scanAgain:'फिर से स्कैन करें', found:'मिल गया', manualWarn:'यह फोटो से चुना गया, स्कैन नहीं हुआ। सुपरवाइज़र जाँचेंगे।', testLabels:'इस प्रीव्यू में कैमरा नहीं — लेबल पर टैप करें', noLabel:'लेबल खराब? फोटो से चुनें', listen:'सुनें', submit:'ERP में भेजें', sending:'भेज रहे हैं…', completed:'ERP में सेव हो गया', pending:'भेजना बाकी', failed:'सेव नहीं हुआ', retry:'फिर कोशिश करें', nextTask:'अगला काम', home:'होम', help:'मदद', sync:'भेजना', mixing:'मिक्सिंग', filling:'भराई', packing:'पैकिंग', dispatch:'डिस्पैच', stopped:'क्या मशीन रुकी थी?', noStop:'नहीं', minutes:'मिनट', check:'जाँचें और भेजें', today:'आज', review:'जाँच', teams:'टीम', machines:'मशीन', ok:'ठीक है', printLabel:'QR लेबल छापें', signOut:'बाहर निकलें', language:'भाषा', waitingSend:'काम भेजना बाकी', allSaved:'आपका सारा काम ERP में सेव है', scanHint:'QR को डिब्बे के अंदर रखें', online:'ऑनलाइन', weak:'कमज़ोर नेटवर्क', offline:'नेटवर्क नहीं', scan:'स्कैन', fixIt:'ठीक करें' },
  mr:{ signIn:'साइन इन', yourMobile:'तुमचा मोबाइल नंबर टाका', smsCode:'SMS कोड टाका', forgotPin:'PIN विसरलात? SMS कोड मिळवा', notFound:'हा नंबर Mahek One मध्ये नाही. नंबर तपासा किंवा HR ला सांगा.', inactive:'तुमचे खाते चालू नाही. ऑफिसमध्ये HR शी बोला.', resend:'कोड पुन्हा पाठवा', resendIn:'पुन्हा पाठवा', whoAreYou:'तुम्ही कोण आहात?', tapPhoto:'तुमच्या फोटोवर टॅप करा', scanBadge:'माझा बॅज स्कॅन करा', enterPin:'तुमचा PIN टाका', notYou:'मी नाही', wrongPin:'PIN चुकीचा आहे. पुन्हा टाका.', scanQR:'QR स्कॅन करा', scanAny:'सुरू करण्यासाठी कोणतेही Mahek लेबल स्कॅन करा', myTasks:'आजचे माझे काम', start:'सुरू करा', cont:'पुढे चालू ठेवा', done:'झाले', next:'पुढे', back:'मागे', isRight:'हेच उत्पादन आहे का?', yes:'होय, बरोबर', wrong:'नाही, चुकीचे', team:'टीम', change:'बदला', used:'वापरले', scanLabel:'लेबल स्कॅन करा', scanAgain:'पुन्हा स्कॅन करा', found:'सापडले', manualWarn:'हे फोटोने निवडले, स्कॅन केले नाही. सुपरवायझर तपासतील.', testLabels:'या प्रिव्ह्यूमध्ये कॅमेरा नाही — लेबलवर टॅप करा', noLabel:'लेबल खराब? फोटोने निवडा', listen:'ऐका', submit:'ERP ला पाठवा', sending:'पाठवत आहे…', completed:'ERP मध्ये जतन झाले', pending:'पाठवणे बाकी', failed:'जतन झाले नाही', retry:'पुन्हा प्रयत्न करा', nextTask:'पुढचे काम', home:'होम', help:'मदत', sync:'पाठवणे', mixing:'मिक्सिंग', filling:'भरणे', packing:'पॅकिंग', dispatch:'डिस्पॅच', stopped:'मशीन बंद पडली होती का?', noStop:'नाही', minutes:'मिनिटे', check:'तपासा आणि पाठवा', today:'आज', review:'तपासणी', teams:'टीम', machines:'मशीन', ok:'ठीक', printLabel:'QR लेबल छापा', signOut:'बाहेर पडा', language:'भाषा', waitingSend:'काम पाठवणे बाकी', allSaved:'तुमचे सर्व काम ERP मध्ये जतन आहे', scanHint:'QR चौकटीत धरा', online:'ऑनलाइन', weak:'कमकुवत नेटवर्क', offline:'नेटवर्क नाही', scan:'स्कॅन', fixIt:'दुरुस्त करा' }
};

export type Lang = keyof typeof L;
export type Words = (typeof L)["en"];

/** Each step title in [English, Hindi, Marathi]. */
export const STEP_T: Record<string, readonly [string, string, string]> = { identify:['Check the product','प्रोडक्ट जाँचें','उत्पादन तपासा'], team:['Who is working','कौन काम कर रहा है','कोण काम करत आहे'], materials:['Scan materials','माल स्कैन करें','माल स्कॅन करा'], output:['How much was made','कितना बना','किती तयार झाले'], sfg:['Scan the base liquid','बेस लिक्विड स्कैन करें','बेस लिक्विड स्कॅन करा'], pack:['Can size and empty cans','डिब्बे का साइज़','डब्याचा आकार'], count:['Count the cans','डिब्बे गिनें','डबे मोजा'], fglot:['Scan the filled cans','भरे डिब्बे स्कैन करें','भरलेले डबे स्कॅन करा'], boxes:['Count the boxes','बॉक्स गिनें','बॉक्स मोजा'], order:['Check the order','ऑर्डर जाँचें','ऑर्डर तपासा'], load:['Scan and load','स्कैन करके लोड करें','स्कॅन करून लोड करा'], checklist:['Final checks','आखिरी जाँच','शेवटची तपासणी'], review:['Check and send','जाँचें और भेजें','तपासा आणि पाठवा'] };
