const fs = require('fs');
const path = require('path');
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('expo/config-plugins');

/**
 * KEEPS THE RECORDER'S MIRRORED CREDENTIAL OUT OF ANDROID'S BACKUP.
 *
 * `MbosLocationService` cannot read `expo-secure-store` — that is another
 * package's cipher and another package's keystore alias, and being wrong about
 * either inside a background service on a phone nobody can recall is not a
 * thing to build. So the app MIRRORS four values into the service's own
 * app-private `SharedPreferences`: the base URL, the device id, and the access
 * and refresh JWTs, in plain text. `FixStore` carries that argument; this file
 * carries its consequence.
 *
 * App-private preferences are included in Android's auto-backup unless
 * something says otherwise, and NOTHING HERE SAID OTHERWISE. `app.json` sets
 * no `android.allowBackup`, and `@expo/config-plugins`' own `getAllowBackup`
 * defaults to TRUE and is applied on every `expo prebuild` — which this app
 * runs from scratch on every release, `android/` being gitignored. So the
 * shipped manifest has read `android:allowBackup="true"` with no backup rules
 * under it, and the refresh token has been going to Google's backup and,
 * on Android 12 and up, across a device-to-device transfer.
 *
 * WHY THE OTHER HALF OF THE APP DOES NOT HAVE THIS PROBLEM. `expo-secure-store`
 * keeps its values under a key in the Android keystore, and a keystore key is
 * never backed up — a restore hands the app ciphertext it cannot open, the
 * session fails, and the salesman signs in again. That is the safe direction
 * and it is why the mirror is the one file that carries a USABLE credential
 * across a device boundary. A restored phone would hold a refresh token and a
 * `deviceId` for a binding that belongs to another handset, and its recorder
 * would post somebody else's route as that device while the app beside it was
 * signed out — which is not a leak so much as two phones claiming to be one.
 *
 * WHY NOT `allowBackup="false"`, WHICH WOULD ALSO FIX IT. Because it would fix
 * far more than it was asked to. Backup is what carries the rest of the
 * handset's state — the SQLite book, the outbox, the media queue — onto a
 * salesman's replacement phone, and whether a man who has lost his handset
 * gets his unsent day back is a decision about the product with a real cost on
 * either side. Nobody has asked that question, and answering it as a side
 * effect of a credential concern is how a decision gets made without anybody
 * deciding it. If Mahek does want it, it is one line in `app.json`
 * (`android.allowBackup: false`) and this plugin becomes harmless rather than
 * wrong.
 *
 * TWO FILES BECAUSE THERE ARE TWO MECHANISMS, and a rule written for one is
 * simply not read by the other. `android:fullBackupContent` is what Android 11
 * and below obey — which is a real share of the cheap handsets this app runs
 * on — and `android:dataExtractionRules` is what Android 12 and above obey.
 * The second needs BOTH of its sections: `<cloud-backup>` alone leaves
 * device-to-device transfer including everything, which is the copy that
 * actually reaches a second working phone.
 */

/** The preferences file the service writes. See the note beside PREFS_SOURCE. */
const PREFS_FILE = 'MbosLocationService.xml';

/*
 * THE NAME IS A LITERAL IN TWO PLACES, JOINED ONLY BY A SPELLING — and getting
 * it wrong fails SILENTLY, because an exclusion that names no file excludes
 * nothing and the build is perfectly valid. `src/lib/credential-backup.test.ts`
 * reads `FixStore.kt` and this file as text and pins the pair, which is the
 * same thing `mbos-wire.test.ts` does for the two halves of the sync payload
 * and for the same reason.
 */

const BACKUP_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by plugins/withCredentialBackupRules.js. android/ is rebuilt by
     expo prebuild on every release, so an edit here is erased; edit the plugin.
     Android 11 and below read this file. -->
<full-backup-content>
  <exclude domain="sharedpref" path="${PREFS_FILE}" />
</full-backup-content>
`;

const EXTRACTION_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by plugins/withCredentialBackupRules.js. android/ is rebuilt by
     expo prebuild on every release, so an edit here is erased; edit the plugin.
     Android 12 and above read this file, and read BOTH sections: cloud backup
     and device-to-device transfer are two separate copies and an exclusion
     written for one does not apply to the other. -->
<data-extraction-rules>
  <cloud-backup>
    <exclude domain="sharedpref" path="${PREFS_FILE}" />
  </cloud-backup>
  <device-transfer>
    <exclude domain="sharedpref" path="${PREFS_FILE}" />
  </device-transfer>
</data-extraction-rules>
`;

module.exports = function withCredentialBackupRules(config) {
  /* The resources first. A manifest pointing at an `@xml/` name that does not
     exist is not a warning — aapt refuses the build — so the file has to be on
     disk before the reference to it is, and a dangerous mod is the only place
     in prebuild where writing one is allowed. */
  config = withDangerousMod(config, [
    'android',
    (cfg) => {
      const xmlDir = path.join(cfg.modRequest.platformProjectRoot, 'app/src/main/res/xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'mbos_backup_rules.xml'), BACKUP_RULES);
      fs.writeFileSync(path.join(xmlDir, 'mbos_data_extraction_rules.xml'), EXTRACTION_RULES);
      return cfg;
    },
  ]);

  return withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    application.$['android:fullBackupContent'] = '@xml/mbos_backup_rules';
    application.$['android:dataExtractionRules'] = '@xml/mbos_data_extraction_rules';
    return cfg;
  });
};
